apiVersion: apps/v1
kind: Deployment   #"You are a manager, not a worker."
metadata:
  name: short-server          #The manager's name is short.
spec:
  replicas: 1     #"Always keep 1 running. Not 0, not 2."
  selector:
    matchLabels:
      app: short-server               # (A) which Pods do I manage?
  template:                 # ---- everything below describes a Pod ----
    metadata:
      labels:
        app: short-server             # (B) MUST match (A), and the Service selects on it
    spec:
      containers:
        - name: short-server
          image: shorten/short-server:2709732
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: shorten-secrets
          ports:
            - containerPort: 5000

