apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shorten-dev

resources:
  - ../../base
  - ../../components/postgres      # dev runs Postgres in-cluster

images:
  - name: shorten/ui
    newTag: 2709732-nonroot
  - name: shorten/auth-server
    newTag: 2709732-nonroot
  - name: shorten/short-server
    newTag: 2709732-nonroot

patches:
  - target:
      kind: ConfigMap
      name: shorten-config
    patch: |-
      - op: replace
        path: /data/PUBLIC_BASE_URL
        value: "https://shorten.local/r"
